version: '2'
services:

  fusiondirectory-app:
    container_name: fusiondirectory-app
    restart: always
    image: tiredofit/fusiondirectory:alpine
    ports:
      - 80:80
    depends_on:
      - openldap-fusiondirectory
    environment:
      - VIRTUAL_HOST=fusiondirectory.example.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=fusiondirectory.example.org
      - LETSENCRYPT_EMAIL=yourname@example.org

      - ZABBIX_HOSTNAME=fusiondirectory-app

      - ENABLE_ARGONAUT=FALSE
      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE

      - LDAP1_HOST=openldap-fusiondirectory
      - LDAP1_DOMAIN=example.org
      - LDAP1_BASE_DN=dc=example,dc=org
      - LDAP1_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP1_ADMIN_PASS=password
      - LDAP1_NAME=Production
      - LDAP1_PORT=389

      #- LDAP2_BASE_DN=dc=example,dc=org
      #- LDAP2_ADMIN_DN=cn=admin,dc=example,dc=org
      #- LDAP2_HOST=openldap-fusiondirectory2
      #- LDAP2_ADMIN_PASS=password2
      #- LDAP2_NAME=Development
      #- LDAP2_TLS=TRUE

    volumes:
      - ./logs:/www/logs
      #- ./custom:/assets/fusiondirectory
      #- ./plugins-custom:/assets/plugins-custom

    networks:
      - proxy-tier


networks:
  proxy-tier:
    external:
      name: nginx-proxy
